#!/usr/bin/env python3
"""
项目初始化脚本 - 让 Claude Code 了解项目配置
运行此脚本告诉 Claude 当前项目的设置
"""

import os
import json
from datetime import datetime

# 项目配置信息
PROJECT_CONFIG = {
    "project_name": "Claude Code Project",
    "initialized_at": datetime.now().isoformat(),
    "config_files": {
        "main_config": "claude.md",
        "server_config": ".claude/config.yaml"
    },
    
    "server_info": {
        "host": "2a09:8280:1::92:6611:0",
        "port": 22,
        "username": "root",
        "password": "Solemn520!",
        "remote_path": "/wwwroot/",
        "connection_type": "SFTP"
    },
    
    "code_protection": {
        "enabled": True,
        "max_delete_lines": 5,
        "backup_required": True
    },
    
    "execution_limits": {
        "max_failures": 5,
        "max_tool_retries": 2,
        "max_mcp_calls": 3
    },
    
    "cleanup_patterns": [
        "test_*",
        "temp_*", 
        "debug_*",
        "*.tmp",
        "*.temp"
    ],
    
    "common_tasks": {
        "upload_to_server": "使用 SFTP 上传文件到服务器",
        "test_server_connection": "测试服务器连接状态",
        "backup_code": "创建代码备份",
        "cleanup_temp_files": "清理临时测试文件"
    }
}

def main():
    """初始化项目配置"""
    print("🚀 Claude Code 项目初始化")
    print("=" * 50)
    
    # 创建配置目录
    os.makedirs(".claude", exist_ok=True)
    
    # 保存配置文件
    config_path = ".claude/project_config.json"
    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(PROJECT_CONFIG, f, ensure_ascii=False, indent=2)
    
    print(f"✅ 配置文件已创建: {config_path}")
    print(f"✅ 服务器信息: {PROJECT_CONFIG['server_info']['host']}")
    print(f"✅ 代码保护: {'启用' if PROJECT_CONFIG['code_protection']['enabled'] else '禁用'}")
    
    # 创建 Claude 提示文件
    prompt_file = ".claude/current_context.md"
    with open(prompt_file, 'w', encoding='utf-8') as f:
        f.write(f"""# 当前项目上下文
        
项目已初始化，配置信息：

## 服务器信息
- 地址: {PROJECT_CONFIG['server_info']['host']}
- 端口: {PROJECT_CONFIG['server_info']['port']} 
- 用户: {PROJECT_CONFIG['server_info']['username']}
- 密码: {PROJECT_CONFIG['server_info']['password']}
- 路径: {PROJECT_CONFIG['server_info']['remote_path']}

## 重要文件
- 主配置: claude.md
- 项目配置: .claude/project_config.json

## 使用说明
在与 Claude Code 交互时，请引用此文件的信息来执行任务。

初始化时间: {PROJECT_CONFIG['initialized_at']}
""")
    
    print(f"✅ 上下文文件已创建: {prompt_file}")
    print("\n💡 现在可以对 Claude Code 说:")
    print("   '参考 .claude/current_context.md 文件，上传 xxx 文件到服务器'")

if __name__ == "__main__":
    main()